#!/bin/bash
# https://github.com/alex-dv9/wg-custom
# created by alex-dv9

case $1 in
  pre) if systemctl is-enabled --quiet wg-custom; then systemctl stop wg-custom.service ; fi ;;
  post) if systemctl is-enabled --quiet wg-custom; then systemctl start wg-custom.service & ; fi ;;
esac
