#!/bin/bash

# This script actually part of wg-custom repository (https://github.com/alex-dv9/wg-custom)

case $1 in
  pre) systemctl stop wg-custom.service ;;
  post) systemctl start wg-custom.service & ;;
esac