#!/bin/bash
# https://github.com/alex-dv9/wg-custom
# created by alex-dv9

case $1 in
  pre) if [ -f /etc/systemd/system/multi-user.target.wants/wg-custom.service ]; then 
	 systemctl stop wg-custom.service
	fi ;;
  
  post) if [ -f /etc/systemd/system/multi-user.target.wants/wg-custom.service ]; then 
	 systemctl start wg-custom.service &
	fi ;;
esac
